events {}

http {
  upstream users_service {
    server users:3001;
  }

  upstream appointments_service {
    server appointments:3002;
  }

  server {
    listen 8080;

    location /api/web/auth/google {
      proxy_pass http://users_service/auth/google;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/web/providers {
      proxy_pass http://appointments_service/providers;
      proxy_set_header Host $host;
    }

    location /api/web/slots {
      proxy_pass http://appointments_service/slots;
      proxy_set_header Host $host;
    }

    location /api/web/slots/seed {
      proxy_pass http://appointments_service/slots/seed;
      proxy_set_header Host $host;
    }

    location /api/web/reservations {
      proxy_pass http://appointments_service/reservations;
      proxy_set_header Host $host;
    }

    location /api/web/reservations/ {
      proxy_pass http://appointments_service/reservations/;
      proxy_set_header Host $host;
    }
  }
}